// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2a079281-7c0d-41e9-a6d0-67121243d5e5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iI3HJL7Nh",
    "aws_user_pools_web_client_id": "2ik3gcqiuqbpr1o6n0c5li3d35",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users",
            "region": "us-east-1"
        },
        {
            "tableName": "experiences",
            "region": "us-east-1"
        },
        {
            "tableName": "itineraries",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "users",
            "endpoint": "https://0hkhmt69m7.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "experiences",
            "endpoint": "https://6qud7l5rr8.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "itineraries",
            "endpoint": "https://4brj7niq38.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
