// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:25939791-bf7e-4e6b-9530-d7cb779c9c5c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6Mm0yBhdj",
    "aws_user_pools_web_client_id": "3d70g0llf47lcjoev77c2iblci",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users",
            "region": "us-east-1"
        },
        {
            "tableName": "experiences",
            "region": "us-east-1"
        },
        {
            "tableName": "itinerary",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "crudUsersAPI",
            "endpoint": "https://i5fq9e6naj.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "experiencesAPI",
            "endpoint": "https://ebpmes4x36.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "itineraryAPI",
            "endpoint": "https://ulfe18uzo0.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
