// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:47ba4dc5-1765-4af3-9591-67eb232f77c8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eHTO5yw3w",
    "aws_user_pools_web_client_id": "5bi301krgl1a1fusqtajr54iij",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "experiences",
            "region": "us-east-1"
        },
        {
            "tableName": "users",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "experiences",
            "endpoint": "https://6qud7l5rr8.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "users",
            "endpoint": "https://rbf9smf47i.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
